import { render, screen } from '@testing-library/react';
import App from './App';

// Blank test generated by "react-app" package
test('renders learn react link', () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});
